### ISSUE TITLE
Test Case Idea: More Types

### ISSUE THREAD

**Issue by huangs1** [gkapfham/tada#10]
Right now, there are only test cases for integers and characters. We could add test cases for Strings and Floats.

**Comment by lussierc** [comment]
@huangs1 I think this is a great idea! We should probably do it after addressing Issue #26 which is for adding more types. We should try to do this immediately addressing Issue #26 to make sure everything is being tested. Considering that we should be addressing Issue #26 right now or very soon, this issue should also be addressed in the near future.
