### ISSUE TITLE
Display which Datatype is currently testing

### ISSUE THREAD

**Issue by Lancasterwu** [gkapfham/tada#11]
I think this will be a simple feature. We technically can just use`type` to check. not sure if we need a loop to go through the whole list.

**Comment by lussierc** [comment]
@Lancasterwu I agree, this should be a simple feature to implement. We could probably just use the `type` feature of Python in some capacity to make this work.

**Comment by lussierc** [comment]
After a group discussion between @Lancasterwu, @huangs1, and myself we have determined this issue does not need to be resolved.
