### ISSUE TITLE
Feature Idea: Round Time Calculator

### ISSUE THREAD

**Issue by lussierc** [gkapfham/tada#14]
We should add a feature that calculates the time that each round of the experiment takes to run. It should also calculate the total amount of time that the experiment takes.

**Comment by huangs1** [comment]
I think that is a good idea for trying to make sure that the program is running efficiently. But, this could be implemented toward the end.

**Comment by lussierc** [comment]
@huangs1 I agree, this is something that should be worked on after the program is more functional and it could wait till the end. However, it should be fairly easy to implement so this is an issue that might be able to be tackled at any point in the development process if time allows.

We could use the `time` module/package to tackle this issue and use it to calculate the time per experiment round. We could also calculate the time elapsed for the whole experiment or simply add calculate the time per experiment round and add all of those timings together.

**Comment by huangs1** [comment]
I think this is presented in the results table. So, I'll close this issue.
