### ISSUE TITLE
Spelling Error in the Name of a Function of the Save Module

### ISSUE THREAD

**Issue by huangs1** [gkapfham/tada#15]
There is a spelling error for the method ```save_benchmark_results``` in the save.py file under the tada/tada/util repository. Right now, it is spelled ```save_bencmark_results``` instead of ```save_benchmark_results``` Also, all of the cases when the method is being called, it is spelled ```save_bencmark_results```

**Comment by lussierc** [comment]
Pull request #17 was merged which fixes this issue.
