### ISSUE TITLE
Feature Improvement Idea: Help Feature

### ISSUE THREAD

**Issue by lussierc** [gkapfham/tada#23]
I think we should add a little bit more information to the help feature regarding running the program. 
Currently when the help feature is run the following is displayed: 
```
usage: tada_a_bigoh.py [-h] --directory DIRECTORY --module MODULE --function
                       FUNCTION [--types TYPES [TYPES ...]]

optional arguments:
  -h, --help            show this help message and exit
  --directory DIRECTORY
                        Package directory with functions to analyze (default:
                        None)
  --module MODULE       Module name with functions to analyze (default: None)
  --function FUNCTION   Name of the module's function to analyze (default:
                        None)
  --types TYPES [TYPES ...]
                        Parameter types for function to analyze (default: [])
```
I think we should information that shows a sample `usage` or input in the terminal of what to type as an example of running the program. The `usage` line is helpful, however, it can be a bit confusing if you don't understand it. An example of the `usage` line in action could be very helpful.

I feel this information could be added in a few places, either up by the `usage` line or maybe at the bottom of the `help` feature's displayed output.

**Comment by huangs1** [comment]
@lussierc This is definitely a good idea and would clarify how to run it, a lot. In addition, we could add this to the README file.

**Comment by lussierc** [comment]
@huangs1 That is a good idea, we should add it to the README as well. I also discussed this idea in Issue #5. This would be a fairly easy issue to tackle so we should try to do so soon, possibly in between working on some of the key features that we are currently trying to implement.

**Comment by lussierc** [comment]
This issue was resolved with a sample usage that was added to the bottom of the help section. This was added in Pull Request #33.

Here is the updated help section:
```

🎆  Tada!: auTomAtic orDer-of-growth Analysis! 🎆
    https://github.com/gkapfham/tada
❓  For Help Information Type: python3 tada_a_bigoh.py -h  ❓

usage: tada_a_bigoh.py [-h] --directory DIRECTORY --module MODULE --function
                       FUNCTION [--types TYPES [TYPES ...]]

optional arguments:
  -h, --help            show this help message and exit
  --directory DIRECTORY
                        Package directory with functions to analyze (default:
                        None)
  --module MODULE       Module name with functions to analyze (default: None)
  --function FUNCTION   Name of the module's function to analyze (default:
                        None)
  --types TYPES [TYPES ...]
                        Parameter types for function to analyze (default: [])

Sample usage: python3 tada_a_bigoh.py --directory
/Users/myname/projectdirectory --module modulename.file --function
function_name --types int
```

As a result, I am closing this issue.
