### ISSUE TITLE
Feature Idea: Analyze Benchmarks

### ISSUE THREAD

**Issue by lussierc** [gkapfham/tada#30]
We should make an analyze module/feature that analyzes benchmarks. Maybe it could look at the `JSON` files to do this.

**Comment by huangs1** [comment]
@lussierc This is a great idea. Also, we could use a test case alongside the analyze. ```JSON``` files are a bit hard to read for us. So, we could parse through the files with ```jq```

**Comment by lussierc** [comment]
@huangs1 From the little I know about `jq`, it seems that this could be a good idea!
