### ISSUE TITLE
`README.md` installation explanation error

### ISSUE THREAD

**Issue by Lancasterwu** [gkapfham/tada#4]
In order to correctly use `pipenv run pytest`, we need to install the developer version of Pipenv instead of the application version of Pipenv. 
So instead of `pipenv install`, we need to use `pipenv install --dev`.
Need someone to change the instruction in README.

**Comment by huangs1** [comment]
In the travis.ml file, it has the steps you were talking about. So, we could just drag everything from that file to the readme.md to make it easier/less work to get to.

**Comment by huangs1** [comment]
This issue has been resolved.
