### ISSUE TITLE
Documentation Needed for "Using Tada"

### ISSUE THREAD

**Issue by lussierc** [gkapfham/tada#5]
Though the program is not fully functional yet, at some point we will need to add better documentation in the **"Using Tada"** section of the **README**. Documentation should be added about how to run the program and how to use key features within it.

**Comment by huangs1** [comment]
I think we can split "Using Tada" up into sections like gatorgrader. For example, have a "Running Tada" with arguments and optional arguments that help run the program.

**Comment by lussierc** [comment]
I think some information we should consider adding about running Tada would be:
- Using the help feature `-h`
- How a user would run the program `python3 tada_a_bigoh.py --directory DIRECTORY --module MODULE --function FUNCTION [--types TYPES [TYPES ...]]`
- What the arguments (ex: `function`, `types,` module`, etc.), we could get a lot of this information from the help feature.

**Comment by lussierc** [comment]
We should also try to add an example of actually running the program to test something. What I mean is take this: `python3 tada_a_bigoh.py --directory DIRECTORY --module MODULE --function FUNCTION [--types TYPES [TYPES ...]]` and provide an actual example of this line in use.

**Comment by lussierc** [comment]
When fixing this Issue, we could add examples of TADA running with Speed-Surprises. Or we could consider adding a section just for this. @huangs1 @Lancasterwu @gkapfham

**Comment by lussierc** [comment]
This was addressed by pull request #35.
